### ISSUE TITLE
tx.input -- viout is actually sequence of previous output

### ISSUE THREAD

**Issue by apexpl** [Congyuwang/Rusty-Bitcoin-Explorer#21]
Within the tx.input property, the 'vour' field is actually the sequence of the previous outpoint.

Is there any way to fix?

Thanks,
Matt

**Comment by Congyuwang** [comment]
Exactly. tx.input.vout is supposed to be the sequence of the previous outpoint.

**Comment by apexpl** [comment]
@Congyuwang  -- I'm sorry, and don't mean to come off as argumentative or anything, but no, that's not right.  Here's an example "vin" JSON block from a tx on the testnet, but mainnet is the same format:
~~~
  "vin": [
    {
      "txid": "8be9aed6e69c8ed996857615e3640d3af94acd20c262909bff0c59fdd5629ee9",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "3044022050a5d768f88873aaf312976d34f2c58fa1e61c4018155e59df99f3d0939f8f2102207d612a948c700aea34d30cb3cee727f412b9dc48f5269db151538465a32d6e4c01",
        "032c8c3c6e914ea8d28a30c013cedf57ec711e4258405c8947fd06ef1974bee918"
      ],
      "sequence": 4294967294
    },
    {
      "txid": "494654fc5b1b7a804dd7a6c6639fca6208569bd8961c46ee0027c829c4a0fa9e",
      "vout": 2,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "3044022002938ac59987cd2cfbc81567f875def9d4701af4a2d92f78a6bd2000b865013d022063234d126632455cfed32ef7c39c956a6db5e37b63ca50b60864d4a0ceb0fc3d01",
        "036efcd037511d066b6536528788fb2175e916ea2d993a7e49bea8fd61da75a527"
      ],
      "sequence": 4294967294
    }
  ],
~~~


Within bitcoin_explorer crate, you have the sequence doubled in both, tx.input.vout and tx.input.sequence.  The sequence variable is fine, and that's correct.

However, tx.input.vout is supposed to be the "vout" field as shown in the above JSON object.  It's basically the "n" field of the previous output or UTXO, and lets you determine exactly which output was spent for that input.

Also, while at it, and change of including that "n" field as tx.output.n?  Example JSON object below:

~~~
  "vout": [
    {
      "value": 0.00011000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 04b65d8b04b9cf20de22e3368b2432b942fd8cca OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a91404b65d8b04b9cf20de22e3368b2432b942fd8cca88ac",
        "address": "mfwsTnsMEMGA1jG4jToX5vLhAdwbi167tN",
        "type": "pubkeyhash"
      }
    }
~~~


Then when the above output is spent, the "vout" of the input will be the same as the "n" in the output, in this case 0.

Would there be any chance in fixing these two things?  In exchange, I'll do my part for open source software and shortly (like in a few days) release a create that allows you to scan the blockchain and gather all UTXOs, and place them in a RocksDB.  If you're unwilling to fix them, would you accept a PR from me, or would it be rejected?

Great crate btw though, I love it.

Best,
Matt

**Comment by Congyuwang** [comment]
I see what you mean. I'm wondering which format are you using (`SBlock` or `SBlock`)? the later is a simplified version.

**Comment by apexpl** [comment]
Really sorry to bother you, but I'm blind and Rust docs aren't overly accessible.

Can you give me a quick example of how to grab / translate into fBlock, and subsequence fTransaction?  All I'm doing right now is basically:

    for block in db.iter_block::<fBlock>(100000, 101000) {

        for tx in block.txdata {
            // Process the tx
        //}

    }

Much appreciated if you by chance have the time.

**Comment by Congyuwang** [comment]
This is weird, I think especially <FBlock> directly grabs data from rust-bitcoin crate, even without much modification. I've updated the rust-bitcoin dependency version. Could you try the newer version?

**Comment by Congyuwang** [comment]
To access the vout / prev_txid of each inputs of each transactions:
```rust
for block in db.iter_block::<FBlock>(100000, 101000) {
    for tx in block.txdata {
        let inputs = tx.input;
        for input in inputs {
            let prev_txid = input.previous_output.vout;
            let vout = input.previous_output.vout;
            let script_sig = input.script_sig;
            let sequence = input.sequence;
            let witness = input.witness;
        }
    }
}
```
Are you using the same loop and accessing the same vout field?
