### ISSUE TITLE
Error: block hash not found in block index!

### ISSUE THREAD

**Issue by cameronelliott** [Congyuwang/Rusty-Bitcoin-Explorer#31]
Thanks for creating and maintaining this cool package.

When I run a simple test program (attached) to iterate the blocks, this is the error I get:

```
c@debian-xeon-1225 ~/rust-1 (master) [1]> time cargo r --release
    Finished release [optimized] target(s) in 0.03s
     Running `target/release/rust-1`
thread 'main' panicked at 'block hash not found in block index!', /home/c/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin-explorer-1.2.20/src/parser/block_index.rs:125:18
```

**Any ideas what I should start looking at to identify or fix the issue?**

I am running bitcoin-24.0.1,and using `bitcoin-explorer = "1.2.20"` in my Cargo.toml

I have pruning disabled for bitcoind. Of course bitcoind is stopped when running my test program.

I have no reason to believe there is any consistentcy issues with my .bitcoin/blocks directory.
(In fact `rusty-blockparser` seems to work fine)

Test program:
```rust

use bitcoin_explorer::{BitcoinDB, FConnectedBlock, SConnectedBlock};
use std::path::Path;

fn main() {
    let path = Path::new("/home/c/.bitcoin");
    let db = BitcoinDB::new(path, false).unwrap();

    let block_count = db.get_block_count();

    let total_number_of_transactions = (0..block_count)
        .map(|i| db.get_header(i).unwrap().n_tx)
        .sum::<u32>();

    println!("nblk {}", block_count);

    println!("ntx {}", total_number_of_transactions);
}

```

**Comment by Congyuwang** [comment]
Currently I do not have full block data files. Can you try help me debug this? 

Mainly it boils down to the following function:

https://github.com/Congyuwang/Rusty-Bitcoin-Explorer/blob/1e123886cc4d185824c2e5c61c27597eca38431a/src/parser/block_index.rs#L76-L142

**Comment by Congyuwang** [comment]
These lines select blocks that (either is genesis block, or (has valid script and has data)), and do two things

(1) figure out the highest block.
(2) build an index from block hash to block record (i.e., where is its data stored and so on) in memory.

https://github.com/Congyuwang/Rusty-Bitcoin-Explorer/blob/1e123886cc4d185824c2e5c61c27597eca38431a/src/parser/block_index.rs#L98-L112

The built `block_index_by_block_hash` is used to figure out the longest chain in the block index, while in the process one of the block index cannot be found.

**Comment by Congyuwang** [comment]
The following lines start from the highest block, and reverse to the genesis block, by recursively looking for `blk.block_header.prev_blockhash` in `block_index_by_block_hash`. This process skip potentially existing forks.

https://github.com/Congyuwang/Rusty-Bitcoin-Explorer/blob/1e123886cc4d185824c2e5c61c27597eca38431a/src/parser/block_index.rs#L118-L137

However, in your case, certain `prev_blockhash` is not found in `block_index_by_block_hash`.  There are two possible reasons to test I think:

(1) maybe the condition `record.n_status & BLOCK_VALID_MASK >= BLOCK_VALID_SCRIPTS && record.n_status & BLOCK_HAVE_DATA > 0` is too strong, and it skipped over certain block records when building block_index_by_block_hash.
(2) maybe the current highest block has bad data in it? So its `prev_blockhash` does not refer to a valid block

**Comment by Congyuwang** [comment]
I've updated a branch [block_hash_not_found_fix](https://github.com/Congyuwang/Rusty-Bitcoin-Explorer/blob/block_hash_not_found_fix/src/parser/block_index.rs). And it will print out which block hash is not found and at which height.

So the debugging idea is to see which block hash and which height it is, and see why it is not included in block_index_by_block_hash. More specifically, see what the `BlockIndexRecord.n_status` of that block is.

**Comment by cameronelliott** [comment]
Thank you, thank you for your quick and helpful response.

I am sorry to report it might be a blockchain consistency issue on my end.

This is the tail end of `bitcoind` when run without -daemon:
```
2023-05-25T21:37:58Z init message: Loading block index…
2023-05-25T21:37:58Z Assuming ancestors of block 00000000000000000009c97098b5295f7e5f183ac811fb5d1534040adb93cabd have valid signatures.
2023-05-25T21:37:58Z Setting nMinimumChainWork=00000000000000000000000000000000000000003404ba0801921119f903495e
2023-05-25T21:37:58Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2023-05-25T21:37:58Z Opening LevelDB in /home/c/.bitcoin/blocks/index
2023-05-25T21:37:58Z Opened LevelDB successfully
2023-05-25T21:37:58Z Using obfuscation key for /home/c/.bitcoin/blocks/index: 0000000000000000
bitcoind: chain.cpp:112: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.
fish: Job 1, '~/bitcoin-24.0.1/bin/bitcoind' terminated by signal SIGABRT (Abort)
```

I also just found that https://bitcoin.org/ is offering version 22.0, 
but https://bitcoincore.org/ is offering 24.1
I am not sure which I should be using, but I have been using 24.1

I will try to download the entire BC again, and see what happens with a complete consistent BC.

Thanks!

**Comment by cameronelliott** [comment]
Okay, this was my fault! I'm sorry I took your time for this non-problem! 
I re-downloaded the entire BC, and the test program seems to work without issues.
I am so sorry.

Thank you,
Cameron
