### ISSUE TITLE
Failure to run (secp256k1-sys)

### ISSUE THREAD

**Issue by TomaszKot2** [Congyuwang/Rusty-Bitcoin-Explorer#5]
When I try to run the code i get following error:
error: failed to run custom build command for `secp256k1-sys v0.4.1`

Code:
use bitcoin_explorer::{BitcoinDB, FConnectedBlock, SConnectedBlock};
use std::path::Path;

fn main() {
    let path = Path::new("D:/BTC/Chain");
let db = BitcoinDB::new(path, false).unwrap();
}

Cargo.toml:
[package]
name = "BTC_explorer_rust"
version = "0.1.0"
edition = "2018"
[dependencies]
bitcoin-explorer = { git = "https://github.com/Congyuwang/Rusty-Bitcoin-Explorer" }

I have gcc also installed. System Win10 x64.

**Comment by Congyuwang** [comment]
I used to build this on Windows10 x86, using VS environment.

**Comment by Congyuwang** [comment]
Is there any more error message?

**Comment by TomaszKot2** [comment]
No, in rusty only "failed to run custom build command for secp256k1-sys v0.4.1"

When running cmake on cmd, just standard information:
Usage
  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

**Comment by Congyuwang** [comment]
I am not sure what your environment is like. So, I cannot really get an answer for you.

FYI, I updated the crate to v1.1.x, which almost guarantees to finish the deserialization (`db.iter_connected_block()`) within 1 hour (in your case, without considering the time for csv writing).
